# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
platform :ios, '10.0'

pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Invites'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'SwiftyJSON'

target 'Konjac' do
end
